version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    image: 'ares:latest'
    container_name: 'laravel'
    ports:
      - 8080:80
    depends_on:
      - postgres
    volumes:
      - ./:/var/www/html
    networks:
      - docker-network

  apache:
    container_name: 'apache'
    image: httpd:latest
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - /home/webserver/asset-registration/public_html/:/usr/local/apache2/htdocs/
    networks:
      - docker-network

  postgres:
    container_name: 'postgres'
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: ares_db
      POSTGRES_PASSWORD: aresdb12
      POSTGRES_USER: ares_user
    image: postgres:latest
    networks:
      - docker-network


networks:
  docker-network:

    driver: bridge
